### ISSUE TITLE
Convert Nebula 30X .cram file to 23andMe format

### ISSUE THREAD

**Issue by annjain** [WGSExtract/WGSExtract.github.io#1]
I have downloaded my Nebula genomics 30X .cram file. I would like to extract the complete list of snps and genotypes resulting in a 23andme style output file. I have successfully installed WGSExtract and discovered that I need to convert the .cram file to .bam for input to WGSExtract. 

I am running samtools version 1.9 on Windows 10 Pro with a 64-bit operating systen and OMP_THREAD_LIMIT=18.

I am working from a powershell and have already gotten past a MD5 checksum mismatch. However, I have now run into the next snag, bgzf_useek():

> samtools.exe view -b -S --input-fmt-option ignore_md5=1 --reference hg38.fa file.cram > file.bam

bgzf_useek() on reference file: Invalid argument
[E::cram_decode_slice] Unable to fetch reference #4 19076893..19115491
[E::cram_next_slice] Failure to decode slice
[main_samview] truncated file.

I would very much appreciate any of the following:
1. a fix to my current command to get past the bgzf_useek() snag.
2. a better command for the .cram to .bam conversion.
3. a means for WGSExtract to accept the original .cram as input.

**Comment by RandyHarr** [comment]
When we add the button to WGS Extract, it will likely simply be  the following command:
samtools view -b -T yourrefgenome.fa -o your.bam your.cram

The correct reference genome for Nebula Genomics (as of June 2020 using the BGI lab) is:
WGSExtract/reference_genomes/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

We put a doc up on the Facebook group (Dante Labs and Nebula Genomics Customers) file server for the conversion: https://bit.ly/31TeqYH . I will make sure everything said here is covered there for any following your path in the future.

It is not a good idea to ignore the md5 checksum error.  That is fundamental to the CRAM format.  The samtools command will download the individual sequence name models (SNs or chromosomes) from the EBI server based on the md5 checksum embedded in the header.  If you are getting a checksum failure, it is likely because the model you are supplying is not what the CRAM was created from.  It must be exactly the same.  Same patches, etc. The checksum error says the reference you supplied checksum is not the same as the CRAM header checksum.  CRAM gets its benefit by basically doing a pseudo pileup and storing column-order as opposed to segment row-order.  As most of the base-pairs are identical to the reference, this gives it more opportunity for compression.  Without the correct reference, it cannot recreate your data.

You can run the command without specifying a reference and avoid the md5 checksum error (likely).  It will just be slower as it grabs the reference model from the EBI server, a chromosome at a time, based on the md5 signature. This model is always stored, uncompressed, in your home directory by samtools.  So make sure you have a few gigabyte spare there. Whether you specify the reference or not, it creates this local, by chromosome copy. of the model.  Specifying the correct reference simply saves the download time of a few gigabytes of data.

I had numerous problems getting the CRAM downloaded without error and then ever running the CRAM to BAM conversion without error. And this with a fiber connection! It was not even consistent in where the error would occur.  After having success using a friends i9-based Mac, I got a new computer and it seemed to solve the problem (even though the old one passed detailed memory and disk checks).  Converting the CRAM to a BAM will stress any disk, memory and CPU system.  The CRAM is often 40-50 GB, resulting in an 80 GB BAM, and intermediate files of a few hundred gigabytes.  The CRAM to BAM conversion is more stressful on the resources than an alignment (FASTQ -< BAM formation). But the feeling is the storage saved makes up for the extra compute resources.  The CRAM, because of its compression type and the md5 checksums, is much more susceptible to single bit errors in the download and processing. Whether introduced during download, disk storage or retrieval, or memory storage or retrieval.  If you get the md5 checksum error without specifying the reference, then your hardware is likely the issue.

**Comment by annjain** [comment]
Thank you so much!

I'm running your command:

> samtools view -b -T GCA_000001405.15_GRCh38_no_alt_analysis_set.fna -o
my.bam my.cram

If the run doesn't finish, I'll retry the .cram download.

Ann E. Jain, PhD
Senior Staff Scientist, Jain Lab
Helen Diller Family Comprehensive Cancer Center
University of California, San Francisco
Email:   ann@jainlab.org          Phone: *415-514-3302*
Address: UCSF, Ann E. Jain, PhD
               HDFCCC,  Box 0128
               1450 3rd Street, Room 364
               San Francisco, CA 94143

**Comment by RandyHarr** [comment]
No problem.  -b and -o name.ext are usually both required to maintain the correct compressed output format.  Let us know if this solves your problem so we can close the issue thread out.  Takes 30 to 300 minutes to run; depending on your processor.

**Comment by annjain** [comment]
The run went much further than the last time (59 GB .bam file from the 47
GB .cram file) , but the run still truncated at 2h 45 min.

> samtools view -b -T GCA_000001405.15_GRCh38_no_alt_analysis_set.fna -o
my.bam my.cram
[samfaipath] build FASTA index...

bgzf_useek() on reference file: Invalid argument
[E::cram_decode_slice] Unable to fetch reference #12 40205424..40243825
[E::cram_next_slice] Failure to decode slice
[main_samview] truncated file.

Thanks again for your help. As you noted, there are several possible
failure points including the original .cram download or my hardware.

This is my personal data, so I might have to stop here.

Best,
Ann Jain

Ann E. Jain, PhD
Senior Staff Scientist, Jain Lab
Helen Diller Family Comprehensive Cancer Center
University of California, San Francisco
Email:   ann@jainlab.org          Phone: *415-514-3302*
Address: UCSF, Ann E. Jain, PhD
               HDFCCC,  Box 0128
               1450 3rd Street, Room 364
               San Francisco, CA 94143

**Comment by RandyHarr** [comment]
Similar error. Could simply be an incorrectly indexed or no index reference (faidx, see CRAM doc). But more likely corrupt CRAM or bad hardware. Based on the slow time, you are on a slower platform. If you can try on an advanced generation machine (macbook pro i7 or i9, etc), it could help. 

Curious, are you on an AMD processor? Mine was an old 2 physical core AMD in an HP motherboard. Sometimes a particular program can use an instruction set in a way that uncovers a compatibility issue.

**Comment by annjain** [comment]
Intel core i9, 18 cores

Thanks again for your help!

**Comment by RandyHarr** [comment]
The 18 core version implies a more recent stepping / model.  An i9-9900 (8 core) in a MacPro Laptop only takes 20 minutes to convert a ~45GB Nebula CRAM file to a ~80GB BAM.  That includes using "-@ 16" and having 64GB DRAM.  We are still trying to work out in WGS Extract how best to auto detect and set the processor core parameter (@).  It is limited as to when it gets a benefit (BGZIP is one of them).

I would work on getting another download of your CRAM to start.  Add the "-@ 16" parameter.  The memory parameter (e.g. -m 2G to specify 2GBytes per thread) is utilized when sorting the BAM. Note sure if the conversion requires a sort or not. But can't hurt to add it.  If 18 threads, 2GBytes per thread, then you need a machine with at least 40GB DRAM.  4GB is a base OS space usually needed for Win10 and MacOSX.

I never determined where the source of my error was introduced.  Just that I had 3-5 single bit differences over the 45GB CRAM files between multiple downloads. Once I changed the platform, that went away. Am on a i9-9900 (8 core), 40 GB DRAM, 2 TB NMEd SSD machine on the same fiber connection now and never once had a hiccup reoccur.  So not sure what in the old environment contributed to the issue (intermittent 8 year old memory not detected by deep memory tests; hard disk single bit errors not showing up in SMART analysis, etc)  All I can say is encryption and CRAM encode/decode both use serial hashing algorithms which are very susceptible to one bit errors introducing catastrophic failure. Standard ZIP compression not so much.

**Comment by RandyHarr** [comment]
Have you resolved your problem? Can we close the issue?

**Comment by annjain** [comment]
Hi Randy,

Thank you for your help and please close the issue.

After several attempts, my machine never completed the conversion of the
cram to a bam file.

I'm giving up for now.

Thanks,
Ann

Ann E. Jain, PhD
Senior Staff Scientist, Jain Lab
Helen Diller Family Comprehensive Cancer Center
University of California, San Francisco
Email:   ann@jainlab.org          Phone: *415-514-3302*
Address: UCSF, Ann E. Jain, PhD
               HDFCCC,  Box 0128
               1450 3rd Street, Room 364
               San Francisco, CA 94143

**Comment by RandyHarr** [comment]
OK. will close it for now.  As your machine should be plenty powerful enough, and this should be a simple task, I would suggest trying to re-download the file. If you would like me to try, send me an email at randy@mycuz.us. (Or I could have my daughter stop by to pick up your Nebula login credentials.  She lives nearby. You included your signature line in your email responses.  I lived on upper Beaumont nearby in the 1980s.)
