### ISSUE TITLE
Download link is broken for the hs38d1s

### ISSUE THREAD

**Issue by 4Liberty** [WGSExtract/WGSExtract.github.io#16]
Hello, I have a bam file from https://sequencing.com. However, when I try to download their reference genome hs38d1s, WGS Extract gives an error. Therefore, I checked the source link from genomes.vcf file and I noticed that its OneDrive link is not accessible. 

hs38d1s,WGSE,hs38d1s.fa.gz,hs38d1s.fa.gz, **https://api.onedrive.com/v1.0/shares/s!AgorjTSMFYpjgR0QualUlHx53-0U/root/content,hs38d1s** (by Sequencing),2581,Num,hs38d1s ([Sequencing.com](http://sequencing.com/); hs38d1+22_KI270879v1_alt) (@WGSE)

![screenshot2](https://github.com/WGSExtract/WGSExtract.github.io/assets/85907940/3960218a-69d6-43a5-8ef3-a78b994265c4)

Could someone please provide me an alternative download link for the hg38d1s? I couldn't find it anywhere on the internet. I am an amateur in this field and would appreciate any help.

**Comment by RandyHarr** [comment]
Thank you for doing the more thorough unvestigation.  It does appear ALL the files with links to our MS Onedrive server are missing.  Investigating now and likely have to restore from backup.

A few weeks ago we restructed to remove all references to Google Drive due to the continual changes and breaking of features that Google keeps introducing for large file support; even with paid accounts. We suspect during this shuffling is when the reference directory was removed.

hs38d1 is a custom model we built because Sequencing.com decided to develop a custom model for their BAM alignment.  You will not find it anywhere.  We will get it restored soon.  Worse case, you may have to update your genomes.csv with a file we provide if we cannot restore the same links. Now that Bitly supports MS Onedrive, we may change them to Bitly short links that we can retarget anywhere -- so even an update to genomes.csv will not be necessary.

Give me an hour to fix everything.

**Comment by RandyHarr** [comment]
Rolling back to a date in MS Onedrive is not like MS Windows which unwinds the journaling file system.  It is more like Google Docs where it simply creates a new version, as of that date and time, of what things looked like at that previous date.  Thus updating all files and changing all their share URLs.  So now everything is broken.  While we work to fix everything (installs, upgrades, etc), here is the URL for the reference genome you are looking for.  It should work for 24-48 hours (at minimum) but may change once we finish everything.  I could not supply the genomes.csv file because I was not sure what version you are running.  So just edit in the URL for hs38d1 in your seed_genomes.csv file with the below.  Make sure to then save it as a comma-separated CSV file. 


https://api.onedrive.com/v1.0/shares/s!AgorjTSMFYpjgR0Xw6wgBhTDzh_v/root/content

I will close the comment for now because once the system is working for everyone, it will work for you.  Once working again, simply rerun the installer to get the new files with links.
