### ISSUE TITLE
Cygwin64 Error

### ISSUE THREAD

**Issue by asticore** [WGSExtract/WGSExtract.github.io#22]
Keep getting same error on windows. 

Tried, running as admin, tried Beta, Alpha & Dev versions. Tried putting in Programs files & in downloads. Even tried installing Cygwin64 from the original site. None of these solutions seams to work with V4.

[CWINDOWSsystem32cmd.exe.txt](https://github.com/WGSExtract/WGSExtract.github.io/files/14100132/CWINDOWSsystem32cmd.exe.txt)

Above link is the output file from CMD.

**Comment by RandyHarr** [comment]
From a read of your log file, I see a few hiccups occurring.  I think they may all revolve around trying to install in "c:\Program Files".  Whether you have administrative permissions or not, the software cannot install in 
Program Files".  Only executables are allowed there.  Not all the libraries and temporary files the program needs to install can be stored there.  (Maybe, if we were more dedicated to the Windows platform exclusively, we could set things up to be split between the "Program Files", ProgramData and Windows Registry.)  

The Downloads folder can be installed into but will usually triggers security issues with Windows.  Windows does not like executing programs out of Downloads or Documents. Some have been able to do it.  Most cannot.

It is best to install in your home folder: %USERPROFILE%.  So if your user name is Joe, then C:\Users\Joe\WGSExtractv4 would be an ideal location. The root folder c:\WGSExtractv4 is also another good one. As is a different disk like d:\WGSExtractv4.

While we try to make sure spaces can be accepted in file names and paths, it appears that may also be a problem later on -- although it could be simply a compounding of errors that results in the appearance that is an issue. 

You cannot install and use Cygwin64 yourself directly.  Because the bioinformatic tool binaries we ship are compiled to a specific version of the various tools.   So our static, captured Cygwin64 release must be used if you use our bioinformatic tools.

Let us know if this solves your issue.

**Comment by RandyHarr** [comment]
I should add that it was discovered that the space in a path problem was reintroduced into the latest available installer.  Known and fixed in the next release not yet out.  But that we can recreate the "program files" permission to write problem in some levels of Windows due to default ACL setups of that area.  Basically, the closer you are to the Home release vs the Developer release, the more permission problems you encounter.  I think we have changed all documentation to recommend not using that area.  If not, please let me know where we need to update it.  Previous reports of permission and space in "program files" are resolved once you change to an area like suggested above.
