### ISSUE TITLE
Impossible to download some genome reference during setup

### ISSUE THREAD

**Issue by Patogym** [WGSExtract/WGSExtract.github.io#6]
Impossible to download some genome reference during setup.
The 3 files : hs37d5.fa.gz ; hs38.fa.gz ; human_glk_v37.fasta.gz are impossible to download via the install_win10.bat.
there are 5 retries for each file, but never succeed in downloading them.
So impossible to use the program
All other genome reference files are ok
Tested several times for 3 days now

**Comment by RandyHarr** [comment]
Can you provide any more details on why they seem to fail? Also, where are you located (country) and what is your internet speed and reliability? What was the download speed of the other reference genomes?

**Comment by Patogym** [comment]
Hi,

 

They are downloaded at 1500MB/s (10minutes or so each), and at the end of the transfer of each of these 3 files, it is writing FTP problem, retry… 5 retries left, 4 , 3 ,2 ,1…

And at the end, these 3 files are on the hard disk, but cannot be opened by gzip (and the sizes are not good at all)

All others denomes references files are ok

I did it several times on 3 differents computers, same problem

 

Regards

 

Patrick Semavoine 

SEMATRONIK SARL 
www.sematronik.com 
455 chemin font de ribe et vallon 
06610 LA GAUDE 
Tel : 06.27.53.18.38 
Fax : 04.92.11.08.99

 

De : Randy H ***@***.***> 
Envoyé : mercredi 23 juin 2021 14:17
À : WGSExtract/WGSExtract.github.io ***@***.***>
Cc : Patogym ***@***.***>; Manual ***@***.***>
Objet : Re: [WGSExtract/WGSExtract.github.io] Impossible to download some genome reference during setup (#6)

 

Can you provide any more details on why they seem to fail? Also, where are you located (country) and what is your internet speed and reliability? What was the download speed of the other reference genomes?

**Comment by Patogym** [comment]
Hi,

They are downloaded at 1500MB/s (10minutes or so each), and at the end of the transfer of each of these 3 files, it is writing FTP problem, retry… 5 retries left, 4 , 3 ,2 ,1…
And at the end, these 3 files are on the hard disk, but cannot be opened by gzip (and the sizes are not good at all)
All others denomes references files are ok
I did it several times on 3 differents computers, same problem

Regards

**Comment by Patogym** [comment]
and if i launch setup again, here is message :
![Capture](https://user-images.githubusercontent.com/86340395/123097084-0e65bf80-d430-11eb-867b-1167fc5c9283.JPG)

**Comment by RandyHarr** [comment]
And where are you located?  It is a US government server and so possibly it is blocking some countries / areas.  I did not think such rules applied to this field but possible I suppose.  One other during Alpha testing reported a similar problem.  They were located in Finland, from what I recall.  No others have reported such an issue with over 100 downloads to date.

I forgot the modified BWA-kit shell file is in the same folder and named bwa-kit-gen-ref.sh.  But it relies on downloading 2 of those same 3 files as the base for creating the 4 others.  So likely not much help.

**Comment by Patogym** [comment]
I'm in France

**Comment by Patogym** [comment]
Is there another wayo to download these 3 files ? FTP link ? so that i can try to add them in directory

**Comment by RandyHarr** [comment]
The primary file locations we use in the script are on NIH servers in the USA.  The hs37d5 and hs38 files are at ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz
and ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz ; respectively as used in the script.  There are alternate locations for these two. 

They are on other NIH servers at ftp://ftp.ncbi.nlm.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz and ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz ; respectively. This may just be an alias for the same server. 

They are both on EBI servers in Cambridge, UK at ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz and ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa ; respectively. (Note that the latter one here is not compressed and so over 3 GB in size.)  These links do not work reliably for many in the USA or other locations.
 
human_g1k_v37 can be created from hs37d5 via the script given before.  It is primarily located at ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz with alternate locations of 
https://storage.cloud.google.com/genomics-public-data/references/hs37d5/hs37d5.fa.gz and ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz  That first link is a Google Genomics (Verily) storage location.

I should point out that hs38DH is very similar to these three you mention and on most of those same servers.  So am confused that you are not reporting a problem with it as well.

The first three you are having trouble with are in the original WGS Extract v2 release.  So if you had that installed, you could upgrade from it and those three would already exist and not have to be downloaded again.  That release is still located on our Google Drive server at http://bit.ly/3afRl6O . See the user manual for how to install v2 and then the v3 as an upgrade / overlay of that.  Simply, put the initial v3 installer files in the same directory as your v2 installation.  Then run Upgrade_Win10.bat instead of Install_Win10.bat.

The v2 release did not have hs38dh.  But that you would normally only need that if using some of the 1KGenome Phase 3 and other scientific samples.

**Comment by RandyHarr** [comment]
It appears your hs38dh did not download correctly either.  You should delete the four files to allow them to download again.  We are not able to apply file size checks nor MD5 checksums in the installer script at this time to verify a proper download to trigger an attempt to download again.  It will have to wait until we can move the code into Python.

**Comment by Patogym** [comment]
Hi, I succeeded in downloading them on the ftp serve in UK.
And you are right, now hs38dh is corrupted also, impossible to download it via installer
Do you have other links for me ?

**Comment by RandyHarr** [comment]
Glad to hear that is an option.  I will see if I can add the EBI servers as an alternate.  Or at least try to document that in the manual.

The spreadsheet attached to the Reference Genome study will always have all known / found links (bit.ly/34CO0vj).  If you ever run into problems again.  Here are the hs38DH ones extracted from there.
Original: ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
Alternate (Verily): https://storage.cloud.google.com/genomics-public-data/references/hg38/v0/Homo_sapiens_assembly38.fasta
EBI version: 
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
(note: none have been compressed. So will be 3GB to download.  The Process script will compress it properly and bring it back down to about 1GB.)
(note: the file is often named GRCh38_full_analysis_set_plus_decoy_hla.fa but is actually the original hs38dh.fa.gz)

I will mark this as solved / closed for now.  With the knowledge we will try to make the system more robust and use multiple servers in the future (beside simply downloading only when really needed).
